site_name: Trash Idle Post-mortem
docs_dir: 'Post-mortem'
theme:
  name: material
  locale: en
  palette:
    scheme: slate
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.footer
extra:
   social:
     - icon: fontawesome/brands/Discord
       link: https://discordapp.com/users/699375169398898688
       name: Discord
nav:
  - Introduction: 'index.md'
  - Post-mortem:
    - Initial Ideas: 'Post-mortem 01.md'
    - Development: 'Post-mortem 02.md'
    - Playtesting The Cauchy: 'Post-mortem 03.md'
    - The Central Limit Theorem: 'Post-mortem 04.md'
    - Conclusion And Future Ideas: 'Post-mortem 05.md'
  - Generating Cauchy Samples: 'Generating Cauchy Samples.md'
  - Under Construction - Truncating The Cauchy: 'Truncating The Cauchy.md'
